$(function(){
    $("#b").mouseenter(function(){
        $("#b").fadeTo(300,1);
    })
    $("#b").mouseleave(function(){
        $("#b").fadeTo(300,0);
    })
    $("#c").mouseenter(function(){
        $("#c").fadeTo(300,1);
    })
    $("#c").mouseleave(function(){
        $("#c").fadeTo(300,0);
    })
    $("#d").mouseenter(function(){
        $("#d").fadeTo(300,1);
    })
    $("#d").mouseleave(function(){
        $("#d").fadeTo(300,0);
    })
    $("#e").mouseenter(function(){
        $("#e").fadeTo(300,1);
    })
    $("#e").mouseleave(function(){
        $("#e").fadeTo(300,0);
    })
    $("#f").mouseenter(function(){
        $("#f").fadeTo(300,1);
    })
    $("#f").mouseleave(function(){
        $("#f").fadeTo(300,0);
    })
    $("#g").mouseenter(function(){
        $("#g").fadeTo(300,1);
    })
    $("#g").mouseleave(function(){
        $("#g").fadeTo(300,0);
    })
    $("#h").mouseenter(function(){
        $("#h").fadeTo(300,1);
    })
    $("#h").mouseleave(function(){
        $("#h").fadeTo(300,0);
    })
    $("#i").mouseenter(function(){
        $("#i").fadeTo(300,1);
    })
    $("#i").mouseleave(function(){
        $("#i").fadeTo(300,0);
    })
    $("#j").mouseenter(function(){
        $("#j").fadeTo(300,1);
    })
    $("#j").mouseleave(function(){
        $("#j").fadeTo(300,0);
    })
    $("#k").mouseenter(function(){
        $("#k").fadeTo(300,1);
    })
    $("#k").mouseleave(function(){
        $("#k").fadeTo(300,0);
    })
    $("#m").mouseenter(function(){
        $("#m").fadeTo(300,1);
    })
    $("#m").mouseleave(function(){
        $("#m").fadeTo(300,0);
    })
    $("#n").mouseenter(function(){
        $("#n").fadeTo(300,1);
    })
    $("#n").mouseleave(function(){
        $("#n").fadeTo(300,0);
    })
})
$(function(){
    $(".div_1").click(function(){
        $("#ul1").toggle(300);
    })
    $(".div_2").click(function(){
      $("#ul2").toggle(300);
  })
  $(".div_3").click(function(){
      $("#ul3").toggle(300);
  })
  })
